POST http://localhost:3009/admin/
Content-Type: application/json

{
    "username" : "nagendra@02",
    "password" : "nagendra@123",
    "name" : "ANEGONDI NAGENDRA BABU"
}


###

POST http://localhost:3009/admin_login/
Content-Type: application/json

{
    "username" : "nagendra@02",
    "password" : "nagendra@123"
}

###

GET http://localhost:3009/admin_details/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5hZ2VuZHJhQDAwNCIsImlhdCI6MTcwMDc2MTM2N30.9CHW8Uif-3QmT7M3Q6O-b_hBdVjXHNZCGZXLbo4gIfU

###

GET http://localhost:3009/admin/profile/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5hZ2VuZHJhQDAyIiwiaWF0IjoxNzAxMTg5NTUzfQ.R3Isy2YDtD-ChhrBW7Q_11HZN7pijxcS2wOiYA2U1eo

###

POST http://localhost:3009/schools/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5hZ2VuZHJhQDAyIiwiaWF0IjoxNzAxMTgyNDY4fQ.Q1D6mQATUUCL_kw8mJL5y0Rxq7ePwwN7daHbkQdEfkk

{
    "schoolName" : "BHEERAM SREEDHAR REDDY INTERNATIONAL SCHOOL",
    "username" : "sris@gmail.com",
    "password" : "gautam@123",
    "adminId" : "fc81af72-7a15-414e-882e-600d00c67641"
}

###

GET http://localhost:3009/admin/fc81af72-7a15-414e-882e-600d00c67641/schools/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5hZ2VuZHJhQDAyIiwiaWF0IjoxNzAxMTg5NTUzfQ.R3Isy2YDtD-ChhrBW7Q_11HZN7pijxcS2wOiYA2U1eo