POST http://localhost:3009/admin/
Content-Type: application/json

{
    "username" : "vijaya@1",
    "password" : "vijaya@1234",
    "name" : "Vijaya Lakshmi"
}


###

POST http://localhost:3009/admin_login/
Content-Type: application/json

{
    "username" : "vijaya",
    "password" : "vijaya@123"
}

